/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="MobileOperatorMasterForm"
 */
public class MobileOperatorMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** operatorName property */
	private String operatorName;

	/** operatorDesc property */
	private String operatorDesc;

	/** operatorId property */
	private int operatorId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the operatorName.
	 * @return String
	 */
	public String getOperatorName() {
		return operatorName;
	}

	/** 
	 * Set the operatorName.
	 * @param operatorName The operatorName to set
	 */
	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	/** 
	 * Returns the operatorDesc.
	 * @return String
	 */
	public String getOperatorDesc() {
		return operatorDesc;
	}

	/** 
	 * Set the operatorDesc.
	 * @param operatorDesc The operatorDesc to set
	 */
	public void setOperatorDesc(String operatorDesc) {
		this.operatorDesc = operatorDesc;
	}

	/** 
	 * Returns the operatorId.
	 * @return int
	 */
	public int getOperatorId() {
		return operatorId;
	}

	/** 
	 * Set the operatorId.
	 * @param operatorId The operatorId to set
	 */
	public void setOperatorId(int operatorId) {
		this.operatorId = operatorId;
	}
}