/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="MobileCardSalesForm"
 */
public class MobileCardSalesForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** cardId property */
	private int cardId;

	/** userId property */
	private int userId;

	/** operatorId property */
	private int operatorId;

	/** saleDate property */
	private String saleDate;

	/** saleId property */
	private int saleId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the cardId.
	 * @return int
	 */
	public int getCardId() {
		return cardId;
	}

	/** 
	 * Set the cardId.
	 * @param cardId The cardId to set
	 */
	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	/** 
	 * Returns the userId.
	 * @return int
	 */
	public int getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the operatorId.
	 * @return int
	 */
	public int getOperatorId() {
		return operatorId;
	}

	/** 
	 * Set the operatorId.
	 * @param operatorId The operatorId to set
	 */
	public void setOperatorId(int operatorId) {
		this.operatorId = operatorId;
	}

	/** 
	 * Returns the saleDate.
	 * @return String
	 */
	public String getSaleDate() {
		return saleDate;
	}

	/** 
	 * Set the saleDate.
	 * @param saleDate The saleDate to set
	 */
	public void setSaleDate(String saleDate) {
		this.saleDate = saleDate;
	}

	/** 
	 * Returns the saleId.
	 * @return int
	 */
	public int getSaleId() {
		return saleId;
	}

	/** 
	 * Set the saleId.
	 * @param saleId The saleId to set
	 */
	public void setSaleId(int saleId) {
		this.saleId = saleId;
	}
}