/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="MobileCardDetailsForm"
 */
public class MobileCardDetailsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** validityDate property */
	private String validityDate;
private String operatorname;
	/** cardNumber property */
	private String cardNumber;

	/** operationId property */
	private int operationId;

	/** cardId property */
	private int cardId;

	/** cardName property */
	private String cardName;

	/** cardStatus property */
	private String cardStatus;

	/** cardAmount property */
	private int cardAmount;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the validityDate.
	 * @return String
	 */
	public String getValidityDate() {
		return validityDate;
	}

	/** 
	 * Set the validityDate.
	 * @param validityDate The validityDate to set
	 */
	public void setValidityDate(String validityDate) {
		this.validityDate = validityDate;
	}

	/** 
	 * Returns the cardNumber.
	 * @return String
	 */
	public String getCardNumber() {
		return cardNumber;
	}

	/** 
	 * Set the cardNumber.
	 * @param cardNumber The cardNumber to set
	 */
	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	/** 
	 * Returns the operationId.
	 * @return int
	 */
	public int getOperationId() {
		return operationId;
	}

	/** 
	 * Set the operationId.
	 * @param operationId The operationId to set
	 */
	public void setOperationId(int operationId) {
		this.operationId = operationId;
	}

	/** 
	 * Returns the cardId.
	 * @return int
	 */
	public int getCardId() {
		return cardId;
	}

	/** 
	 * Set the cardId.
	 * @param cardId The cardId to set
	 */
	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	/** 
	 * Returns the cardName.
	 * @return String
	 */
	public String getCardName() {
		return cardName;
	}

	/** 
	 * Set the cardName.
	 * @param cardName The cardName to set
	 */
	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	/** 
	 * Returns the cardStatus.
	 * @return String
	 */
	public String getCardStatus() {
		return cardStatus;
	}

	/** 
	 * Set the cardStatus.
	 * @param cardStatus The cardStatus to set
	 */
	public void setCardStatus(String cardStatus) {
		this.cardStatus = cardStatus;
	}

	/** 
	 * Returns the cardAmount.
	 * @return int
	 */
	public int getCardAmount() {
		return cardAmount;
	}

	/** 
	 * Set the cardAmount.
	 * @param cardAmount The cardAmount to set
	 */
	public void setCardAmount(int cardAmount) {
		this.cardAmount = cardAmount;
	}

	public String getOperatorname() {
		return operatorname;
	}

	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname;
	}
}