/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="StampOrderMasterForm"
 */
public class StampOrderMasterForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** orderStatus property */
	private String orderStatus;

	/** userId property */
	private int userId;

	/** orderAmount property */
	private int orderAmount;

	/** employeId property */
	private int employeId;

	/** orderId property */
	private int orderId;

	/** orderDate property */
	private String orderDate;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the orderStatus.
	 * @return String
	 */
	public String getOrderStatus() {
		return orderStatus;
	}

	/** 
	 * Set the orderStatus.
	 * @param orderStatus The orderStatus to set
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	/** 
	 * Returns the userId.
	 * @return int
	 */
	public int getUserId() {
		return userId;
	}

	/** 
	 * Set the userId.
	 * @param userId The userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/** 
	 * Returns the orderAmount.
	 * @return int
	 */
	public int getOrderAmount() {
		return orderAmount;
	}

	/** 
	 * Set the orderAmount.
	 * @param orderAmount The orderAmount to set
	 */
	public void setOrderAmount(int orderAmount) {
		this.orderAmount = orderAmount;
	}

	/** 
	 * Returns the employeId.
	 * @return int
	 */
	public int getEmployeId() {
		return employeId;
	}

	/** 
	 * Set the employeId.
	 * @param employeId The employeId to set
	 */
	public void setEmployeId(int employeId) {
		this.employeId = employeId;
	}

	/** 
	 * Returns the orderId.
	 * @return int
	 */
	public int getOrderId() {
		return orderId;
	}

	/** 
	 * Set the orderId.
	 * @param orderId The orderId to set
	 */
	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	/** 
	 * Returns the orderDate.
	 * @return String
	 */
	public String getOrderDate() {
		return orderDate;
	}

	/** 
	 * Set the orderDate.
	 * @param orderDate The orderDate to set
	 */
	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}
}