/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 *
 * 
 * XDoclet definition:
 * @struts.form name="StampOrderDetailsForm"
 */
public class StampOrderDetailsForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** orderId property */
	private int orderId;

	/** qtyOredered property */
	private int qtyOredered;

	/** itemId property */
	private int itemId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the orderId.
	 * @return int
	 */
	public int getOrderId() {
		return orderId;
	}

	/** 
	 * Set the orderId.
	 * @param orderId The orderId to set
	 */
	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	/** 
	 * Returns the qtyOredered.
	 * @return int
	 */
	public int getQtyOredered() {
		return qtyOredered;
	}

	/** 
	 * Set the qtyOredered.
	 * @param qtyOredered The qtyOredered to set
	 */
	public void setQtyOredered(int qtyOredered) {
		this.qtyOredered = qtyOredered;
	}

	/** 
	 * Returns the itemId.
	 * @return int
	 */
	public int getItemId() {
		return itemId;
	}

	/** 
	 * Set the itemId.
	 * @param itemId The itemId to set
	 */
	public void setItemId(int itemId) {
		this.itemId = itemId;
	}
}